//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"encoding/json"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataLayerConfig) DeepCopyInto(out *DataLayerConfig) {
	*out = *in
	if in.InjectDefaults != nil {
		in, out := &in.InjectDefaults, &out.InjectDefaults
		*out = new(bool)
		**out = **in
	}
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]DataLayerSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Discovery != nil {
		in, out := &in.Discovery, &out.Discovery
		*out = new(DiscoveryConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CrossReplicaSyncInterval != nil {
		in, out := &in.CrossReplicaSyncInterval, &out.CrossReplicaSyncInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.CrossReplicaPublishTimeout != nil {
		in, out := &in.CrossReplicaPublishTimeout, &out.CrossReplicaPublishTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataLayerConfig.
func (in *DataLayerConfig) DeepCopy() *DataLayerConfig {
	if in == nil {
		return nil
	}
	out := new(DataLayerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataLayerExtractor) DeepCopyInto(out *DataLayerExtractor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataLayerExtractor.
func (in *DataLayerExtractor) DeepCopy() *DataLayerExtractor {
	if in == nil {
		return nil
	}
	out := new(DataLayerExtractor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataLayerSource) DeepCopyInto(out *DataLayerSource) {
	*out = *in
	if in.Extractors != nil {
		in, out := &in.Extractors, &out.Extractors
		*out = make([]DataLayerExtractor, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataLayerSource.
func (in *DataLayerSource) DeepCopy() *DataLayerSource {
	if in == nil {
		return nil
	}
	out := new(DataLayerSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryConfig) DeepCopyInto(out *DiscoveryConfig) {
	*out = *in
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = new(EndpointDiscoveryConfig)
		**out = **in
	}
	if in.Peers != nil {
		in, out := &in.Peers, &out.Peers
		*out = new(PeerDiscoveryConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryConfig.
func (in *DiscoveryConfig) DeepCopy() *DiscoveryConfig {
	if in == nil {
		return nil
	}
	out := new(DiscoveryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointDiscoveryConfig) DeepCopyInto(out *EndpointDiscoveryConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointDiscoveryConfig.
func (in *EndpointDiscoveryConfig) DeepCopy() *EndpointDiscoveryConfig {
	if in == nil {
		return nil
	}
	out := new(EndpointDiscoveryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointPickerConfig) DeepCopyInto(out *EndpointPickerConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.FeatureGates != nil {
		in, out := &in.FeatureGates, &out.FeatureGates
		*out = make(FeatureGates, len(*in))
		copy(*out, *in)
	}
	if in.Plugins != nil {
		in, out := &in.Plugins, &out.Plugins
		*out = make([]PluginSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SchedulingProfiles != nil {
		in, out := &in.SchedulingProfiles, &out.SchedulingProfiles
		*out = make([]SchedulingProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DataLayer != nil {
		in, out := &in.DataLayer, &out.DataLayer
		*out = new(DataLayerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.FlowControl != nil {
		in, out := &in.FlowControl, &out.FlowControl
		*out = new(FlowControlConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RequestHandler != nil {
		in, out := &in.RequestHandler, &out.RequestHandler
		*out = new(RequestHandlerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SaturationDetector != nil {
		in, out := &in.SaturationDetector, &out.SaturationDetector
		*out = new(SaturationDetectorConfig)
		**out = **in
	}
	if in.Parser != nil {
		in, out := &in.Parser, &out.Parser
		*out = new(ParserConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointPickerConfig.
func (in *EndpointPickerConfig) DeepCopy() *EndpointPickerConfig {
	if in == nil {
		return nil
	}
	out := new(EndpointPickerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EndpointPickerConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in FeatureGates) DeepCopyInto(out *FeatureGates) {
	{
		in := &in
		*out = make(FeatureGates, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeatureGates.
func (in FeatureGates) DeepCopy() FeatureGates {
	if in == nil {
		return nil
	}
	out := new(FeatureGates)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowControlConfig) DeepCopyInto(out *FlowControlConfig) {
	*out = *in
	if in.MaxBytes != nil {
		in, out := &in.MaxBytes, &out.MaxBytes
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MaxRequests != nil {
		in, out := &in.MaxRequests, &out.MaxRequests
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.DefaultRequestTTL != nil {
		in, out := &in.DefaultRequestTTL, &out.DefaultRequestTTL
		*out = new(v1.Duration)
		**out = **in
	}
	if in.NoEndpointRequestTTL != nil {
		in, out := &in.NoEndpointRequestTTL, &out.NoEndpointRequestTTL
		*out = new(v1.Duration)
		**out = **in
	}
	if in.DefaultPriorityBand != nil {
		in, out := &in.DefaultPriorityBand, &out.DefaultPriorityBand
		*out = new(PriorityBandConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultNegativePriorityBand != nil {
		in, out := &in.DefaultNegativePriorityBand, &out.DefaultNegativePriorityBand
		*out = new(PriorityBandConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.PriorityBands != nil {
		in, out := &in.PriorityBands, &out.PriorityBands
		*out = make([]PriorityBandConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SaturationDetector != nil {
		in, out := &in.SaturationDetector, &out.SaturationDetector
		*out = new(SaturationDetectorConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowControlConfig.
func (in *FlowControlConfig) DeepCopy() *FlowControlConfig {
	if in == nil {
		return nil
	}
	out := new(FlowControlConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParserConfig) DeepCopyInto(out *ParserConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParserConfig.
func (in *ParserConfig) DeepCopy() *ParserConfig {
	if in == nil {
		return nil
	}
	out := new(ParserConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerDiscoveryConfig) DeepCopyInto(out *PeerDiscoveryConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerDiscoveryConfig.
func (in *PeerDiscoveryConfig) DeepCopy() *PeerDiscoveryConfig {
	if in == nil {
		return nil
	}
	out := new(PeerDiscoveryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginSpec) DeepCopyInto(out *PluginSpec) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginSpec.
func (in *PluginSpec) DeepCopy() *PluginSpec {
	if in == nil {
		return nil
	}
	out := new(PluginSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PriorityBandConfig) DeepCopyInto(out *PriorityBandConfig) {
	*out = *in
	if in.MaxBytes != nil {
		in, out := &in.MaxBytes, &out.MaxBytes
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MaxRequests != nil {
		in, out := &in.MaxRequests, &out.MaxRequests
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.DefaultRequestTTL != nil {
		in, out := &in.DefaultRequestTTL, &out.DefaultRequestTTL
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PriorityBandConfig.
func (in *PriorityBandConfig) DeepCopy() *PriorityBandConfig {
	if in == nil {
		return nil
	}
	out := new(PriorityBandConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestHandlerConfig) DeepCopyInto(out *RequestHandlerConfig) {
	*out = *in
	if in.Parsers != nil {
		in, out := &in.Parsers, &out.Parsers
		*out = make([]ParserConfig, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestHandlerConfig.
func (in *RequestHandlerConfig) DeepCopy() *RequestHandlerConfig {
	if in == nil {
		return nil
	}
	out := new(RequestHandlerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SaturationDetectorConfig) DeepCopyInto(out *SaturationDetectorConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SaturationDetectorConfig.
func (in *SaturationDetectorConfig) DeepCopy() *SaturationDetectorConfig {
	if in == nil {
		return nil
	}
	out := new(SaturationDetectorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingPlugin) DeepCopyInto(out *SchedulingPlugin) {
	*out = *in
	if in.Weight != nil {
		in, out := &in.Weight, &out.Weight
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingPlugin.
func (in *SchedulingPlugin) DeepCopy() *SchedulingPlugin {
	if in == nil {
		return nil
	}
	out := new(SchedulingPlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingProfile) DeepCopyInto(out *SchedulingProfile) {
	*out = *in
	if in.Plugins != nil {
		in, out := &in.Plugins, &out.Plugins
		*out = make([]SchedulingPlugin, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingProfile.
func (in *SchedulingProfile) DeepCopy() *SchedulingProfile {
	if in == nil {
		return nil
	}
	out := new(SchedulingProfile)
	in.DeepCopyInto(out)
	return out
}
